
services:
  backend:
    build: ./backend   # <--- usa el Dockerfile del backend
    image: lacastrilp/cocoa-backend:latest
    container_name: backend_app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend-vite   
    image: lacastrilp/cocoa-frontend:latest
    container_name: frontend_app
    env_file: .env
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres_local
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Project_app123

volumes:
  postgres_data: